
///////////////////////////////////////////////////////////////////////////
// Append to SPLPROT.2DA                                                 //
///////////////////////////////////////////////////////////////////////////
// Weapon Profs
ACTION_FOR_EACH weapon_prof IN
      89  // BASTARDSWORD
      90  // LONGSWORD
      91  // SHORTSWORD
      92  // AXE
      93  // TWOHANDEDSWORD
      94  // KATANA
      95  // SCIMITAR
      96  // DAGGER
      97  // WARHAMMER
      115 // CLUB
      98  // SPEAR
      99  // HALBERD
      100 // FLAILMORNINGSTAR
      101 // MACE
      102 // QUARTERSTAFF
      103 // CROSSBOW
      104 // LONGBOW
      105 // SHORTBOW
      106 // DART
      107 // SLING
      111 // SLING
      112 // SLING
      113 // SLING
      114 // SLING
    BEGIN
      APPEND ~splprot.2da~ ~prof_gteq_%weapon_prof%%TAB%%weapon_prof%%TAB%-1%TAB%4~ UNLESS ~prof_gteq_%weapon_prof% ~
    END

// Update all imported files so they point in the correct direction.
COPY_EXISTING ~splprot.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW rows cols
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY_FORMER rows row 0 ~stat~
      
      // WEAPON PROF ----------------------------------------------------------//
      // BASTARDSWORD
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_89~ BEGIN 
        SET prof_gteq_89 = %row%
      // LONGSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_90~ BEGIN
        SET prof_gteq_90 = %row%
      // SHORTSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_91~ BEGIN
        SET prof_gteq_91 = %row%
      // AXE
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_92~ BEGIN
        SET prof_gteq_92 = %row%
      // TWOHANDEDSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_93~ BEGIN
        SET prof_gteq_93 = %row%
      // KATANA
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_94~ BEGIN
        SET prof_gteq_94 = %row%
      // SCIMITAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_95~ BEGIN
        SET prof_gteq_95 = %row%
      // DAGGER
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_96~ BEGIN
        SET prof_gteq_96 = %row%
      // WARHAMMER
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_97~ BEGIN
        SET prof_gteq_97 = %row%
      // CLUB
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_115~ BEGIN
        SET prof_gteq_115 = %row%
      // SPEAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_98~ BEGIN
        SET prof_gteq_98 = %row%
      // HALBERD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_99~ BEGIN
        SET prof_gteq_99 = %row%
      // FLAILMORNINGSTAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_100~ BEGIN
        SET prof_gteq_100 = %row%
      // MACE
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_101~ BEGIN
        SET prof_gteq_101 = %row%
      // QUARTERSTAFF
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_102~ BEGIN
        SET prof_gteq_102 = %row%
      // CROSSBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_103~ BEGIN
        SET prof_gteq_103 = %row%
      // LONGBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_104~ BEGIN
        SET prof_gteq_104 = %row%
      // SHORTBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_105~ BEGIN
        SET prof_gteq_105 = %row%
      // DART
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_106~ BEGIN
        SET prof_gteq_106 = %row%
    // SLING
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_107~ BEGIN
        SET prof_gteq_107 = %row%

    // WEAPON STYLE ---------------------------------------------------------//
    // 2HANDED
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_111~ BEGIN
        SET prof_gteq_111 = %row%
    // SWORDANDSHIELD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_112~ BEGIN
        SET prof_gteq_112 = %row%
    // SINGLEWEAPON
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_113~ BEGIN
        SET prof_gteq_113 = %row%
    // 2WEAPON
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_gteq_114~ BEGIN
        SET prof_gteq_114 = %row%
    END
    END

// Resistances
DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	~override~
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END

//	Array of Restistance / Stat#
ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY	BEGIN
	~CRUSH~		=>	22
	~ACID~		=>	17
	~COLD~		=>	15
	~ELEC~		=>	16
	~FIRE~		=>	14
	~PIERC~		=>	23
	~POISN~		=>	74
	~MAGIC~		=>	73
	~MSSL~		=>	24
	~SLASH~		=>	21
	~MFIRE~		=>	19
	~MCOLD~		=>	20
END
ACTION_PHP_EACH	DMG_ARRAY AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 100	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY2	BEGIN
	~ACID2~		=>	17
	~COLD2~		=>	15
	~ELEC2~		=>	16
	~FIRE2~		=>	14
	~MAGIC2~		=>	73
	~MFIRE2~		=>	19
	~MCOLD2~		=>	20
	~MSSL2~		=>	24
END
ACTION_PHP_EACH	DMG_ARRAY2 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 0	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

APPEND ~splprot.2da~ ~C0HTSTR 39 -1 1~ UNLESS ~C0HTSTR ~
APPEND ~splprot.2da~ ~C0HTDEX 39 -1 1~ UNLESS ~C0HTDEX ~
APPEND ~splprot.2da~ ~C0HTCON 39 -1 1~ UNLESS ~C0HTCON ~
APPEND ~splprot.2da~ ~C0HTINT 39 -1 1~ UNLESS ~C0HTINT ~
APPEND ~splprot.2da~ ~C0HTWIS 39 -1 1~ UNLESS ~C0HTWIS ~
APPEND ~splprot.2da~ ~C0HTCHR 39 -1 1~ UNLESS ~C0HTCHR ~
APPEND ~splprot.2da~ ~C0_MAX_HP_GT 1 -1 4~ UNLESS ~C0_MAX_HP_GT ~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTSTR~ BEGIN
	    SET C0HTSTR = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTDEX~ BEGIN
	    SET C0HTDEX = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTCON~ BEGIN
	    SET C0HTCON = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTINT~ BEGIN
	    SET C0HTINT = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTWIS~ BEGIN
	    SET C0HTWIS = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTCHR~ BEGIN
	    SET C0HTCHR = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MAX_HP_GT~ BEGIN
	    SET C0_MAX_HP_GT = %row%
	  END
	PRETTY_PRINT_2DA
	END
	